flake8
ros-visualization/rqt_console pull request #7
Opened 2018-10-20 00:42 UTC by mlautman

updating to flake8

2018-10-22 18:25 UTC, brawner requested changes

2018-10-22 18:25 UTC, brawner commented on src/rqt_console/console_widget.py
> +            newfilter, FilterWrapperWidget(
Is there a tuple missing? Does append automatically create a tuple here?

2018-10-22 18:25 UTC, brawner commented on src/rqt_console/console_widget.py
> +            newfilter, FilterWrapperWidget(
Tuple parens are missing here

2018-10-23 03:38 UTC, mlautman commented on src/rqt_console/console_widget.py
> +            newfilter, FilterWrapperWidget(
great catch!

2018-10-23 03:48 UTC, mlautman commented
@brawner fixed

2018-10-23 17:06 UTC, mlautman commented
Comments addressed. Merging per @brawner's instructions

2018-10-23 17:06 UTC, merged